services:
  - type: web
    name: wematrust-banking
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_TYPE
        value: file
    healthCheckPath: /