services:
  - type: web
    name: wematrust-banking
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BASE_URL
        value: https://wematrust-banking.onrender.com
    healthCheckPath: /
    autoDeploy: true
    branch: main
    nodeVersion: 18
